module.exports = {
    header: [
        { id: 'KSCHL', title: 'KSCHL' },
        { id: 'VKORG', title: 'VKORG' },
        { id: 'PRODH1', title: 'PRODH1' },
        { id: 'PRODH2', title: 'PRODH2' },
        { id: 'KUNNR', title: 'KUNNR' },
        { id: 'KVGR1', title: 'KVGR1' },
        { id: 'KDGRP', title: 'KDGRP' },
        { id: 'KVGR2', title: 'KVGR2' },
        { id: 'KDKG1', title: 'KDKG1' },
        { id: 'KDKG2', title: 'KDKG2' },
        { id: 'KDKG3', title: 'KDKG3' },
        { id: 'KDKG4', title: 'KDKG4' },
        { id: 'KDKG5', title: 'KDKG5' },
        { id: 'MVGR1', title: 'MVGR1' },
        { id: 'MATNR', title: 'MATNR' },
        { id: 'KZBZG', title: 'KZBZG' },
        { id: 'KSTBM', title: 'KSTBM' },
        { id: 'KBETR', title: 'KBETR' },
        { id: 'KONWA', title: 'KONWA' },
        { id: 'KPEIN', title: 'KPEIN' },
        { id: 'KMEIN', title: 'KMEIN' },
        { id: 'ANZAUF', title: 'ANZAUF' },
        { id: 'DATAB', title: 'DATAB' },
        { id: 'DATBI', title: 'DATBI' },
        { id: 'LTX01', title: 'LTX01' },
        { id: 'LTX02', title: 'LTX02' },
        { id: 'LTX03', title: 'LTX03' },
        { id: 'KBSTAT', title: 'KBSTAT' }
    ],
    subHeader: {
        KSCHL: 'Condition Type',
        VKORG: 'Sales Organization',
        PRODH1: 'Principal',
        PRODH2: 'Principal Business Division',
        KUNNR: 'Customer Code',
        KVGR1: 'Customer Group 1',
        KDGRP: 'Customer Group',
        KVGR2: 'Customer Group 2',
        KDKG1: 'CCR Bid type',
        KDKG2: 'CCR Customer type',
        KDKG3: 'CCR Corp SA group',
        KDKG4: 'CCR Cust Loc group',
        KDKG5: 'CCR Cust Pr Gr',
        MVGR1: 'Material Group 1',
        MATNR: 'Material Number',
        KZBZG: 'Scale Basis',
        KSTBM: 'Minimum  Based on Scale',
        KBETR: 'Rate\\Amount',
        KONWA: 'Rate Unit\\Currency',
        KPEIN: 'Condition Pricing Unit',
        KMEIN: 'Condition Unit of Measure',
        ANZAUF: 'One time Deal',
        DATAB: 'Valid From',
        DATBI: 'Valid To',
        LTX01: 'Internal Comment',
        LTX02: 'Text Permit',
        LTX03: 'Concluding Comment',
        KBSTAT: 'Processing Status for Condition'
    }
}
